### ISSUE TITLE
homebrew clones every run

### ISSUE THREAD

**Issue by aaronjensen** [osxc/legacy-common#11]
Every time I run ansible the `clone homebrew` step takes several seconds even though it is already cloned/installed.

**Comment by rricard** [comment]
Maybe related to #10, can you tell me if it's solved now ?

**Comment by aaronjensen** [comment]
nope, not solved. still slow on that step. Also, every brew install afterwards is slow too, as if it's doing a force or an upgrade or something. Ideally it'd zip right through if I'd already run it once.

**Comment by rricard** [comment]
Ok, I see what you mean ... I'll open a followup issue for that :)
